### ISSUE TITLE
Strange server crash when updating from pre 215 to 216 with error Trying to access unbound value: ResourceKey[minecraft:block / integrateddynamics:menril_torch_stone]

### ISSUE THREAD

**Issue by musicbynumbers** [CreativeMD/LittleTiles#1282]
Hi! 

I've got a strange server crash when updating from pre 215 to 216 with error saying "Trying to access unbound value: ResourceKey[minecraft:block / integrateddynamics:menril_torch_stone]

This is on MC 1.21.1 with neoforge 21.1.228

see crash report below
https://mclo.gs/WGxt8mk

and debug log
https://mclo.gs/m5uW0mK

I will say that I had this same error when updating the mod "Charta" and the mod there managed to fix it somehow but not quite sure what he did :) or how integrated dynamics is even related to little tiles at all!

https://github.com/lucaargolo/charta/issues/23
https://github.com/lucaargolo/charta/issues/22

I did also update integrated terminals at the same time but reverting that didn't fix the error, only reverting little tiles did it.

Let me know if you need anything!

**Comment by CreativeMD** [comment]
Honestly this does not seem to be related to LittleTiles. At least I cannot see any connection. Have you made sure you have to same version on client and server? Because in 216 there is a crash on server side, you might had a version mismatch. The newest version fixes this crash and should also fix your issue.

**Comment by musicbynumbers** [comment]
Yeah.. It's a strange one as the charta mod has no connection to menril torches either :)

I pretty sure it was the same version on both as I manage the client install via curseforge the copy it over to the server and since it is a server crash I'm assuming I didn't mess it up but.. I'll try the next one and see :)

I have an absurd amount of mods so things like this happen from time to time!

**Comment by musicbynumbers** [comment]
Tested and the last update seems to have fixed it and mc now loads fine. :)
