### ISSUE TITLE
V1.6.0-pre060_ Mc1.20.1 cannot work on rubidium0.6.5

### ISSUE THREAD

**Issue by Xing-C** [CreativeMD/LittleTiles#893]
I cannot start the game from version v1.6.0-pre058_mc1.20.1 to version LittleTiles_ALPHA_v1.6.0-pre060_mc1.20.1

For some reason, I had to use the old version of rubidium, Because the Oculus light shadow loader relies on it (Rubidium 0.6.5)

Here are the errors:

[20Sep2023 14:26:42.616] [Worker-ResourceReload-5/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event FMLClientSetupEvent dispatch for modid littletiles
java.lang.NoClassDefFoundError: me/jellysquid/mods/sodium/client/model/light/data/HashLightDataCache
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at team.creative.littletiles.client.mod.rubidium.pipeline.LittleRenderPipelineTypeRubidium.<init>(LittleRenderPipelineTypeRubidium.java:8) ~[LittleTiles_ALPHA_v1.6.0-pre060_mc1.20.1.jar%23317!/:1.6.0-pre060]
	at team.creative.littletiles.client.mod.rubidium.RubidiumInteractor.<clinit>(RubidiumInteractor.java:8) ~[LittleTiles_ALPHA_v1.6.0-pre060_mc1.20.1.jar%23317!/:1.6.0-pre060]
	at team.creative.littletiles.client.mod.rubidium.RubidiumManager.init(RubidiumManager.java:24) ~[LittleTiles_ALPHA_v1.6.0-pre060_mc1.20.1.jar%23317!/:1.6.0-pre060]
	at team.creative.littletiles.client.LittleTilesClient.setup(LittleTilesClient.java:215) ~[LittleTiles_ALPHA_v1.6.0-pre060_mc1.20.1.jar%23317!/:1.6.0-pre060]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%23139!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%23139!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23139!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23139!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[language-java-47.1.47.jar%23436!/:47.1]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:124) ~[core-47.1.47.jar%23435!/:47.1]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.jellysquid.mods.sodium.client.model.light.data.HashLightDataCache
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 25 more`

**Comment by CreativeMD** [comment]
Rubidium 0.6.5 is not supported anymore, you will have to use the newer version. Oculus cannot be used at the moment. Sorry there is nothing I can do about it. You will have to wait until it updates.
